name: run-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-legacy:
    name: Legacy Tests (PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.4, 8.0, 8.1]
        laravel: [8.*, 9.*, 10.*]
        stability: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
            php: 8.1
          - laravel: 9.*
            testbench: 7.*
            php: 8.0
          - laravel: 8.*
            testbench: 6.*
            php: 7.4
        exclude:
          - laravel: 10.*
            php: 8.0
          - laravel: 10.*
            php: 7.4
          - laravel: 9.*
            php: 7.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, fileinfo
          coverage: none
          ini-values: extension=fileinfo.so

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ignore-platform-req=ext-fileinfo

      - name: Execute tests
        run: vendor/bin/phpunit --colors=always

  test-laravel12:
    name: Laravel 12 Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']  # Removed 8.1 as Laravel 12 requires 8.2+
        laravel: ['^12.0']
        include:
          - laravel: '^12.0'
            testbench: '^8.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --colors=always

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: [test-legacy, test-laravel12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    needs: [test-legacy, test-laravel12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
        
